server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://database-1.ct6jcofgybfx.us-east-1.rds.amazonaws.com:3306/hr
    username: sourabh
    password: Sourabh123
#    url: jdbc:h2:mem:testDB
#    username: sa
#    password: sa

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true

